//declare action types

const LOG_IN = 'LOG_IN';

const LOG_OUT = 'LOG_OUT';

const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
const EXIT_USER_DETAIL = "EXIT_USER_DETAIL";

export { LOG_IN,LOG_OUT,USER_DETAIL_SUCCESS,EXIT_USER_DETAIL }